# $cluego_api.R
# cluego
#
# $corrplots.R
# plotCorr
# my_custom_cor
#   percent_of_range
# plot_corr_sub
#   my_fn
#   lm_with_cor
#   panel_cor
#   panel_hist
#   panel_lm
#   my_lower
#   my_lower_no_sm
#   my_diag
# pepCorr_logFC
# pepCorr_logInt
# prnCorr_logFC
# prnCorr_logInt
#
# $datasets.R
# 
#
# $dbs.R
# read_fasta
# write_fasta
# load_fasta
# calc_avgpep
#
# $funs.R
# # [1] "#  [2] \"find_mascot_psmraws <-function(filelist = NULL, dat_dir = NULL)\""
# #  [2] "find_mascot_psmraws <-function(filelist = NULL, dat_dir = NULL)"
#
# $global.R
# set_dat_dir
# get_gl_dat_dir
#
# $go.R
# create_db_path
# proc_obo
# proc_gaf
# annot_from_to
# get_full_entrez
# find_human_orthologs
# sp_lookup_go
# find_abbr_species
# set_db_outname
# dl_msig
# proc_gmt
# prepGO
# prepMSig
# map_to_entrez
# Uni2Entrez
# Ref2Entrez
# map_to_entrez_os_name
# create_os_lookup
#   convert_default_os
#
# $gsea.R
# make_gct
# make_cls
# prnGSEA
# fml_gsea
#
# $gspa.R
# pepGSPA
# prnGSPA
# gspaTest
# fml_gspa
# ok_min_size
# gspa_summary_mean
# gspa_summary_limma
# lm_gspa
# prep_gspa
# map_essential
# prnGSPAHM
# gspaHM
# byfml_gspahm
# byfile_gspahm
# gspa_colAnnot
# greedysetcover
#
# $gsva.R
# prnGSVA
# gsvaTest
#
# $histo.R
# plotHisto
# pepHist
# prnHist
#
# $hm.R
# my_pheatmap
# plotHM
# pepHM
# prnHM
#
# $informatics.R
# info_anal
# find_pri_df
# find_sec_df
# vararg_secmsg
#
# $kin.R
# annot_KinSub
# KinSubTest
# anal_KinSub
#
# $lda.R
# plotLDA
# scoreLDA
# pepLDA
# prnLDA
#
# $mds.R
# geom_lower_text
# plotMDS
# plotEucDist
# scoreMDS
# prep_folded_tdata
# scoreEucDist
# pepMDS
# prnMDS
# pepEucDist
# prnEucDist
#
# $metadata.R
# prep_label_scheme
# prep_fraction_scheme
# update_frac_smry
# make_frac_smry
# check_frac_multipsms
# check_exptfrac_raws
# read_metadata
# write_metadata
# check_unnamed_cols
# check_required_cols
# check_optional_cols
# check_empty_rows
# check_tmt126_row
# check_tmt_nc
# check_tmt_plex
# check_channel_prefix
# check_tmt_ref
# rm_fully_empty_tmt_sets
# replace_empty_with_na
# replace_na_with_empty
# check_metadata_integers
# syn_empty_channels
# triv_optcols_at_empty
# recheck_tmt_channels
# check_tmt_rawfiles
# check_tmt_sampleids
# check_tmt_emptyids
# check_tmt_chans_vs_levs
# check_tmt_mixplexes
# check_dups_at_lcms_and_sid
# check_lfq_exptraws
# load_dbs
# load_expts
# reload_expts
# channelInfo
# n_TMT_sets
# n_LCMS
# TMT_plex
# TMT_plex2
# TMT_levels
# simple_label_scheme
# find_mascot_tmtplex
#
# $nmf.R
# analNMF
# plotNMFCon
# plotNMFCoef
# plotNMFmeta
# anal_pepNMF
# anal_prnNMF
# plot_pepNMFCon
# plot_prnNMFCon
# plot_pepNMFCoef
# plot_prnNMFCoef
# plot_metaNMF
#
# $normalization.R
# find_fit_nms
# hfind_fit_nms
# calc_sd_fcts
# center_df
# add_mean_dev
# find_n_comp
# my_which_max
# ok_file_ncomp
# spline_coefs
# normMulGau
# dblTrim
# sumdnorm
#   wt_dnorm
# normSD
# fitKernelDensity
# nmix_params
#
# $outliers.R
# locate_outliers
# dixon_test
# q_dixon
# p_dixon
# q_table
# Dixon_outliers
# Grubbs_outliers
# grubbs_test
# q_grubbs
#           f
# p_grubbs
# Rosner_outliers
#
# $pca.R
# plotPCA
# scorePCA
# pepPCA
# prnPCA
#
# $peptable.R
# newColnames
# hsubColnames
# use_mq_peptable
# use_mf_peptable
# use_mf_prottable
# use_mq_prottable
# fillMFprnnums
# fillMQprnnums
# check_mq_df
# calc_mq_log2r
# extract_mq_ints
# pep_mq_lfq
# pep_mf_lfq
# calc_lfq_log2r
# na_single_lfq
# calcLFQPepNums
# impRefNA
# find_species_centers
# find_species_centers2
# point_in_polygon
# calcLFQPepInts
# spreadPepNums
# countSpecs
# add_spec_counts
# aggrNumLCMS
# pad_grp_samples
# rep_ls_groups
# normPep
# find_ms1filepath
# sep_mbrfiles
# extract_mbry
# groupMZPepZ
# groupMZPepZ2
# med_summarise_keys
# load_prior
# fmt_num_cols
# mergePep
# standPep
# Pep2Prn
# map_peps_prots
# find_prot_family_rows
# my_sum_n
# calcLFQprnnums
# calc_tmt_prnnums
# pep_to_prn
# assign_duppeps
# replace_by_rowone
# impPepNA
# find_mbr_ms1files
# makePepDIANN
# makeProtDIANN
# aggrLCMS_DIANN
#
# $prntable.R
# standPrn
#
# $proteoQ.R
# 
#
# $psmtable.R
# extract_raws
# find_mascot_psmraws <-function(filelist = NULL, dat_dir = NULL)
# find_mq_psmraws
# find_sm_psmraws
# find_mf_psmraws
# find_pq_psmraws
# extract_psm_raws
# set_mascot_colnms
# batchPSMheader
# rmPSMHeaders
# add_mod_conf
# find_mascot_vmods
# add_mascot_pepseqmod
# add_empai
# add_quality_cols
# psm_msplit
# find_shared_prots
# hfind_shared_prots
# add_shared_genes
# add_shared_prot_accs_mf
# add_shared_sm_genes
# procPSMs
# check_raws
# splitPSM_ma
# compile_hdr_mods
# find_mascot_plex
# make_mascot_ratios
# make_mascot_intensities
# add_mascot_raw
# pad_mascot_channels
# pad_mascot_fields
# psm_mcleanup
# cleanupPSM
# mcPSM
# annotPSM
# normPSM
# rm_cols_mqpsm
# groupMZPSM1
# groupMZPSM0
# hrm_lowIntPSMs
# rm_lowIntPSMs
# rm_psm_spikes
# rm_apexrt_outliers
# keep_psm_bestint
# preMZpepLFQ
# postMZpepLFQ
# checkmzLFQRT
# calcLFQPeptide
# calcTMTLFQPeptide
# psm_to_pep
# PSM2Pep
# add_pep_n_apexes
# cleanRTChim
# alignPSMApexs
# rm_RToutliers
# makeLFQXYTS
# cleanPSMYTS
# rm_2RToutliers
# rm_nRToutliers
# updatePSMsd
# fitMS1RT
# calibPSMApexs2
# add_maxquant_pepseqmod
# add_msfragger_pepseqmod
# add_diann_pepseqmod
# add_cols_at
# replace_cols_at
# reloc_col
# reloc_col_after
# reloc_col_after_last
# reloc_col_after_first
# reloc_col_before
# reloc_col_before_last
# reloc_col_before_first
# find_preceding_colnm
# order_psm_cols
# order_mascot_psm_cols
# pad_mq_channels
# splitPSM_mq
# pad_sm_channels
# add_sm_pepseqmod
# pad_mf_channels
# splitPSM_mf
# round_msfmod_decimals
# procMSGFmods
# fml2mass
# join_mgfs
# find_padding_pos
# pad_tmt_channels
# pad_psm_fields
# add_pepseqmod
# add_msgf_pepseqmod
# check_dup_unimods
# splitPSM_mz
# add_pep_retsd
# calc_pep_retsd
# add_n_pepexpz
#
# $purge.R
# lgl_cleanup
# purge_by_cv
# purge_by_qt
# purge_by_n
# psm_mpurge
# purgePSM
# purgePep
#
# $qlfq.R
# haddApexRTs_allsets
# haddApexRTs_oneset
# addApexRTs
# addApexes
# hpepLFQ
# addMBRpeps
# makeLFQSpecies
# fillMBRnaRTs
# pepLFQ
# pepLFQ2
# mpepLFQ
# combine_lfq123
# find_best_lfqvec
# collapseSTY
# mergeSTY
# reduce_lfq_rtstep
# calc_mat_log2s_to_refs
# calc_vec_log2s_to_refs
# calc_mat_sds
# saddMBR
#
# $roadmap.R
# 
#
# $sigtests.R
# rowVars
# filterData
# prepFml
# my_padj
# lm_summary
# model_onechannel
# sigTest
# impute_baseline_ints
# base_sigtest_y
# gen_randoms
# pepSig
# prnSig
#
# $simulData.R
# simulUniprotPSM
# mascot_refseq2uniprot
# maxquant_refseq2uniprot
#
# $specialty.R
# labEffPSM
# procTMT0
# calcTMTLabs
# proteo_hm
#
# $string.R
# annot_stringdb
# stringTest
# anal_prnString
# prepString
# load_stringdbs
#
# $trends.R
# checkdots_analTrend
# analTrend
# plotTrend
# anal_prnTrend
# plot_prnTrend
#
# $utils.R
# prepDM
# find_NorZ
# replace_NorZ_names
# `names_pos<-`
# reorder_files2
# reorderCols
# reorderCols2
# ins_cols_after
# sort_tmt_lcms
# na_zeroIntensity
# not_allzero_rows
# aggrNums
# aggrTopn
# aggrLFQs
# tmt_wtmean
#   my_trim
#   my_wtmean
# TMT_top_n
# not_all_zero
# not_all_NA
# not_all_nan
# is_all_nan
# is_trivial_col
# is_trivial_dbl
# replace_trivial_with_na
# colAnnot
# setHMColor
# setHMlims
# ratio_toCtrl
# imputeNA
#   my_mice
#   handleNA
# pepImp
# prnImp
# sp_lookup
# taxid_lookup
# taxid_lookup_rev
# sp_lookup_Ul
# add_refseq_gene
# add_entrez
# add_custom_entrez
# parse_acc
# parse_fasta
# hparse_fasta
# na_genes_by_acc
# na_species_by_org
# add_fasta_attrs
# add_prot_desc
# na_fasta_name_by_prot_acc
# na_acc_type_to_other
# annotPrn
# annotKin
# save_call
# match_fmls
# match_call_arg
# match_gset_nms
# #' foo
# match_logi_gv
# match_prnSig_scale_log2r
# match_pepSig_scale_log2r
# replace_na_genes
# na_genes_by_acc
# find_pep_pos
# annotPeppos
# subset_fasta
# add_prot_icover
# calc_cover
# to_linfc
# rm_sglval_cols
# cmbn_meta
# gg_imgname
# rm_pval_whitespace
# filters_in_call
# arrangers_in_call
# calc_sd_fcts_psm
# calcSD_Splex
# sd_violin
# rptr_violin
# my_geomean
# count_phosphopeps
# count_pepmiss
# contain_str
# contain_chars_in
# not_contain_str
# not_contain_chars_in
# start_with_str
# end_with_str
# start_with_chars_in
# ends_with_chars_in
# rows_are_all
# rows_are_not_all
# concat_fml_dots
# gn_rollup
# identical_dots
# my_complete_cases
# my_union
# find_fn_bases
# find_fn_exts
# check_dots
# check_depreciated_args
# to_complete_cases
# check_gset_nms
# ok_existing_params
# env_where
# set_cutpoints
# set_cutpoints2
# load_craps
# find_int_cols
# find_ratio_cols
# make_mq_meta
# make_mq_meta2
# update_nodes
# pre_mq_meta
# add_entry_ids
# check_formalArgs
# check_formalArgs2
# set_ggsave_dots
# find_search_engine
# check_ggplot_aes
# prep_range
# find_delim
# recur_flatten
# subset_keepattr
# list_to_dataframe
# find_psmQ_files
# get_col_types
# write_excel_wb
# load_ls_group
# parse_col_select
# parse_filename
# subsetBrukerMGF
# msubsetBrukerMGF
# procBrukerMGF_v1
# procBrukerMGF
# mprocBrukerMGF
# fixBrukerMGF
# mfixBrukerMGF
# check_aes_length
# add_col_rawfile
# load_psmC
# add_scan_id
# my_split1
# my_split2
# my_tolower
# my_toupper
#
# $utils_mzion.R
# find_mod_indexesQ
# deduce_mod_indexes
# hdeduce_mod_indexes
# find_path_ms1
#
# $volcanos.R
# plotVolcano
# pval_complete_cases
# byfml_volcano
# byfile_plotVolcano
# subset_volcano_df
# fullVolcano
# summ_venn
# plot_venn
# gsVolcano
# plot_ibaq
# pepVol
# prnVol
# pepGSPAMap
# prnGSPAMap
# geom_table
# to_csv_
#
# $wrappers.R
# my_dist
# cos_sim
#
# $zzz.R
# .onAttach
#
